/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.Items;
import model.OrderDetails;
import model.Orders;
import service.CustomerService;
import service.ItemsService;
import service.OrderDetailsService;
import service.OrdersService;

/**
 *
 * @author nooby
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        getDateTime();
        Timer t = new Timer(1000, updateClockAction);
        t.start();
        this.tblmodel = (DefaultTableModel)OrderTable.getModel();
        this.setLocationRelativeTo(null);
        btnNewOrder.requestFocus();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        tfTotal = new javax.swing.JTextField();
        lblDateTime = new javax.swing.JLabel();
        GetItemPanel = new javax.swing.JPanel();
        tfItemOrder = new javax.swing.JTextField();
        btnItemOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CompleteOrderPanel = new javax.swing.JPanel();
        btnCompleteOrder = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        btnClearOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblItemMFD = new javax.swing.JLabel();
        lblItemEXP = new javax.swing.JLabel();
        lblICode = new javax.swing.JLabel();
        lblMFD = new javax.swing.JLabel();
        lblEXP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomerNumber = new javax.swing.JButton();
        tfCustomerNumber = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        btnItems = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retail Shop");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        OrderPanel.setPreferredSize(new java.awt.Dimension(845, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total:");

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Amout", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderTable);

        lblDateTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tfItemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemOrderActionPerformed(evt);
            }
        });

        btnItemOrder.setText("Input Item");
        btnItemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GetItemPanelLayout = new javax.swing.GroupLayout(GetItemPanel);
        GetItemPanel.setLayout(GetItemPanelLayout);
        GetItemPanelLayout.setHorizontalGroup(
            GetItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GetItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfItemOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItemOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        GetItemPanelLayout.setVerticalGroup(
            GetItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GetItemPanelLayout.createSequentialGroup()
                .addGroup(GetItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnItemOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfItemOrder))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 123, 10));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Welcome to Retail Shop");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OrderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OrderPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(GetItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPanelLayout.createSequentialGroup()
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GetItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(OrderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 57, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        btnCompleteOrder.setBackground(new java.awt.Color(255, 124, 25));
        btnCompleteOrder.setForeground(new java.awt.Color(0, 0, 0));
        btnCompleteOrder.setText("Complete Order");
        btnCompleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteOrderActionPerformed(evt);
            }
        });

        btnNewOrder.setText("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnClearOrder.setText("Clear Order");
        btnClearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CompleteOrderPanelLayout = new javax.swing.GroupLayout(CompleteOrderPanel);
        CompleteOrderPanel.setLayout(CompleteOrderPanelLayout);
        CompleteOrderPanelLayout.setHorizontalGroup(
            CompleteOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompleteOrderPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnClearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(CompleteOrderPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnCompleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CompleteOrderPanelLayout.setVerticalGroup(
            CompleteOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompleteOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompleteOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btnCompleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Item Information");

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItemCode.setText("Item Code:");

        lblItemMFD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItemMFD.setText("MFD:");

        lblItemEXP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItemEXP.setText("EXP:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemCode)
                            .addComponent(lblItemMFD)
                            .addComponent(lblItemEXP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEXP)
                            .addComponent(lblMFD)
                            .addComponent(lblICode))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode)
                    .addComponent(lblICode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemMFD)
                    .addComponent(lblMFD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemEXP)
                    .addComponent(lblEXP))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCustomerNumber.setText("Get Customer");
        btnCustomerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerNumberActionPerformed(evt);
            }
        });

        lblCustomerName.setBackground(new java.awt.Color(204, 255, 204));
        lblCustomerName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblCustomerName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(tfCustomerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCustomerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCustomerNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnCustomerNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnItems.setText("Items");
        btnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemsActionPerformed(evt);
            }
        });

        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CompleteOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(CompleteOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemOrderActionPerformed
        items.setItemCode(Integer.valueOf(tfItemOrder.getText()));
        try {
            Items i = iservice.getItem(items.getItemCode());
            if(i != null){
            String amount = JOptionPane.showInputDialog("Enter Amount");
            amountusing = Integer.parseInt(amount);
            Double Price = i.getItemPrice() * amountusing;
            tblmodel.addRow(new Object[]{i.getItemName(),amountusing,Price});
            total = total + Price;
            tfTotal.setText(total.toString());
            amountList.add(amountusing);
            itemcodelist.add(items.getItemCode());
            tfItemOrder.setText("");
            lblICode.setText(i.getItemCode().toString());
            lblMFD.setText(i.getItemMFD().toString());
            lblEXP.setText(i.getItemEXP().toString());
            }else{
                JOptionPane.showMessageDialog((Component) null, "Invalid Item", "Alert", JOptionPane.WARNING_MESSAGE);
                tfItemOrder.setText("");
            }
        } catch (SQLException ex) {  
        }
    }//GEN-LAST:event_btnItemOrderActionPerformed

    private void btnCompleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteOrderActionPerformed
        if(lblCustomerName.getText() == ""){
            customer.setCustomerID(0);
        }
        if(tblmodel.getRowCount() == 0){
            JOptionPane.showMessageDialog((Component) null, "Order has no products!!", "Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String getDateTime = lblDateTime.getText();
            String getDate = getDateTime.substring(0, getDateTime.length()-9);
            orders.setTotal(total);
            orders.setCustomerID(customer.getCustomerID());
            orders.setOrderDate(Date.valueOf(getDate));
            oservice.insert(orders);
            orderdetails.setBillID(orders.getBillID());
            billID = orders.getBillID();
                try{
                    for (int i=0; i<itemcodelist.size();i++) {
                        orderdetails.setAmount(Double.valueOf(amountList.get(i)));
                        orderdetails.setItemCode(itemcodelist.get(i));
                        odservice.insert(orderdetails);
                    }
                }
                catch(SQLException ex){
                }
        } catch (SQLException ex) {
        }
        tblmodel.setRowCount(0);
        tfTotal.setText("");
        new PaymentFrame().setVisible(true);
            
            
    }//GEN-LAST:event_btnCompleteOrderActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        String Number = JOptionPane.showInputDialog((Component) null, "Enter Customer Phone Number", "Customer Registered?", JOptionPane.OK_CANCEL_OPTION);
        newOrderAction();
        if(Number != null){
            try {
                customer.setCustomerContactNumber(Integer.valueOf(Number));
                customer = cservice.getCustomer(customer.getCustomerContactNumber());
            } catch (NumberFormatException|SQLException e) {
                JOptionPane.showMessageDialog((Component) null, "Invalid Number", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            lblCustomerName.setText("Welcome  " + customer.getCustomerName());
            lblCustomerName.setVisible(true);
            GetItemPanel.setEnabled(true);
            btnCustomerNumber.setEnabled(true);
            tfCustomerNumber.setEnabled(true);
        }else{
            GetItemPanel.setEnabled(true);
            btnCustomerNumber.setEnabled(true);
            tfCustomerNumber.setEnabled(true);
            
        }
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnClearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOrderActionPerformed
        int a = JOptionPane.showConfirmDialog((Component) null,"Are you Sure?","Confirm?", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
        tblmodel.setRowCount(0);
        tfTotal.setText("");
        GetItemPanel.setEnabled(false);
        }
    }//GEN-LAST:event_btnClearOrderActionPerformed

    private void btnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemsActionPerformed
        new ItemFrame().setVisible(true);
    }//GEN-LAST:event_btnItemsActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        new CustomerFrame().setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void tfItemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemOrderActionPerformed

    }//GEN-LAST:event_tfItemOrderActionPerformed

    private void btnCustomerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerNumberActionPerformed
        try {
            customer.setCustomerID(Integer.valueOf(tfCustomerNumber.getText()));
            customer = cservice.getCustomerViaID(customer.getCustomerID());
            lblCustomerName.setText("Welcome " + customer.getCustomerName());
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCustomerNumberActionPerformed
    
    private void getDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblDateTime.setText(dtf.format(now));
    }
        ActionListener updateClockAction = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                getDateTime();
        }
};

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        MainFrame.total = total;
    }

    public static Integer getBillID() {
        return billID;
    }

    public static void setBillID(Integer billID) {
        MainFrame.billID = billID;
    }
    
    private void initialize(){
        btnItemOrder.setEnabled(false);
        tfItemOrder.setEnabled(false);
        tfCustomerNumber.setEnabled(false);
        btnCustomerNumber.setEnabled(false);
        btnClearOrder.setEnabled(false);
        btnCompleteOrder.setEnabled(false);
    }
    
    private void newOrderAction(){
        btnItemOrder.setEnabled(true);
        tfItemOrder.setEnabled(true);
        btnClearOrder.setEnabled(true);
        btnCompleteOrder.setEnabled(true);
        tfItemOrder.requestFocus();
        while (tfItemOrder.hasFocus() && tfItemOrder.getText() != "") {            
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcDarkOrangeIJTheme.registerCustomDefaultsSource("FlatArcDarkOrangeIJTheme");
        FlatArcDarkOrangeIJTheme.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    Items items = new Items();
    Customer customer = new Customer();
    ItemsService iservice = new ItemsService();
    CustomerService cservice = new CustomerService();
    Orders orders = new Orders();
    OrderDetails orderdetails = new OrderDetails();
    OrdersService oservice = new OrdersService();
    OrderDetailsService odservice = new OrderDetailsService();
    DefaultTableModel tblmodel;
    List<Integer> itemcodelist = new ArrayList<>();
    List<Integer> amountList = new ArrayList<>();
    static Double total = 0.0;
    static Integer billID;
    int amountusing;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CompleteOrderPanel;
    private javax.swing.JPanel GetItemPanel;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton btnClearOrder;
    private javax.swing.JButton btnCompleteOrder;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnCustomerNumber;
    private javax.swing.JButton btnItemOrder;
    private javax.swing.JButton btnItems;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblEXP;
    private javax.swing.JLabel lblICode;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemEXP;
    private javax.swing.JLabel lblItemMFD;
    private javax.swing.JLabel lblMFD;
    private javax.swing.JTextField tfCustomerNumber;
    private javax.swing.JTextField tfItemOrder;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
